// gencity.cpp
//
// This program generates a city scene for POV-Ray.
//
// Written by: Henry Wagner (henryw@panix.com)
// Started: 12/25/96

#include <stdio.h>
#include <stdlib.h>

void main(int argc, char *argv[])
{
   FILE *o;
   int c1, c2, c3, nx, ny, preheight, height, nwn, nws, nwe, nww, wx, wy;

   if (argc < 4) {
      printf("\nERROR: You need to pass in the output filename, nx, and ny\n" );
      exit(0);
   }

   o = fopen(argv[1], "w");
   nx = atoi(argv[2]);
   ny = atoi(argv[3]);

   randomize();

   // Start the file
   fprintf(o, "// %s\n", argv[1] );
   fprintf(o, "//\n" );
   fprintf(o, "// Generated by: Henry Wagner (henryw@panix.com)\n\n" );

   fprintf(o, "#declare POV_City = union {\n" );
   for (c1 = 0; c1 < nx; c1++) {
      for (c2 = 0; c2 < ny; c2++) {
	 preheight = random(100) + 3;
	 height    = preheight * 10;
	 nwn       = random(100);
	 nws       = random(100);
	 nwe       = random(100);
	 nww       = random(100);

	 // fprintf(o, "   difference {\n" );
	 fprintf(o, "   union {\n" );
	 fprintf(o, "      box {\n" );
	 fprintf(o, "         < -200, 0, -200 >,\n" );
	 fprintf(o, "         <  200, %d, 200 >\n", height );
	 fprintf(o, "         texture { Building_Metal }\n" );
	 fprintf(o, "      }\n" );
	 fprintf(o, "      union {\n" );
	 // Create all the north face windows
	 for (c3 = 0; c3 < nwn; c3++) {
	    wx = (random (39) * 10) - 195;
	    wy = random (preheight) * 10;

	    fprintf(o, "         box {\n" );
	    fprintf(o, "            < %d, %d, 199 >,\n", wx, wy );
	    fprintf(o, "            < %d, %d, 201 >\n", wx + 10, wy + 10 );
	    fprintf(o, "         }\n" );
	 }
	 // Create all the south face windows
	 for (c3 = 0; c3 < nws; c3++) {
	    wx = (random (39) * 10) - 195;
	    wy = random (preheight) * 10;

	    fprintf(o, "         box {\n" );
	    fprintf(o, "            < %d, %d, -201 >,\n", wx, wy );
	    fprintf(o, "            < %d, %d, -199 >\n", wx + 10, wy + 10 );
	    fprintf(o, "         }\n" );
	 }
	 // Create all the east facing windows
	 for (c3 = 0; c3 < nwe; c3++) {
	    wx = (random (39) * 10) - 195;
	    wy = random (preheight) * 10;

	    fprintf(o, "         box {\n" );
	    fprintf(o, "            < 199, %d, %d >,\n", wy, wx );
	    fprintf(o, "            < 201, %d, %d >\n", wy + 10, wx + 10 );
	    fprintf(o, "         }\n" );
	 }
	 // Create all the west facing windows
	 for (c3 = 0; c3 < nww; c3++) {
	    wx = (random (39) * 10) - 195;
	    wy = random (preheight) * 10;

	    fprintf(o, "         box {\n" );
	    fprintf(o, "            < -201, %d, %d >,\n", wy, wx );
	    fprintf(o, "            < -199, %d, %d >\n", wy + 10, wx + 10 );
	    fprintf(o, "         }\n" );
	 }

	 fprintf(o, "      texture { Window_Light }\n" );
	 fprintf(o, "      }\n" );
	 fprintf(o, "   translate < %d, 0, %d >\n", c1 * 500, c2 * 500 );
	 fprintf(o, "   }\n" );
      }
   }
   fprintf(o, "}\n" );

   fclose(o);
}