// rotate.cpp
//
// Written by: Henry Wagner

#include <stdio.h>
#include <stdlib.h>

main(int argc, char *argv[])
{
   FILE *o;

   o = fopen("rotate.inc","w");

   fprintf(o, "// rotate.inc\n" );
   fprintf(o, "//\n" );
   fprintf(o, "// Generated by: Henry Wagner\n\n" );

   fprintf(o, "#declare R_FACT = %s\n", argv[1]);

   fclose(o);
   return(0);
}