// mcrypt.cpp
//
// Written by: Henry Wagner (henryw@panix.com)

#include <stdio.h>

main()
{
   int c1, c2;
   FILE *o;

   o = fopen("crypt.inc","w");

   fprintf(o, "// crypt.inc\n" );
   fprintf(o, "//\n" );
   fprintf(o, "// Generated by: Henry Wagner\n" );

   fprintf(o, "#declare Crypt = difference {\n" );
   fprintf(o, "   box {\n" );
   fprintf(o, "      <    0, 10,    0 >,\n" );
   fprintf(o, "      <  102, 30,  102 >\n" );
   fprintf(o, "   }\n" );
   fprintf(o, "   union {\n" );

   for ( c1 = 6; c1 < 102; c1 += 12 ) {
      fprintf(o, "      cylinder {\n" );
      fprintf(o, "         <   -1, 10, %d >,\n", c1 );
      fprintf(o, "         <  103, 10, %d >,\n", c1 );
      fprintf(o, "         5.0\n" );
      fprintf(o, "      }\n" );
      fprintf(o, "      cylinder {\n" );
      fprintf(o, "         < %d, 10,   -1 >,\n", c1 );
      fprintf(o, "         < %d, 10,  103 >,\n", c1 );
      fprintf(o, "         5.0\n" );
      fprintf(o, "      }\n" );
   }

   fprintf(o, "   }\n" );
   fprintf(o, "   texture {\n" );
   fprintf(o, "      T_Stone24\n" );
   fprintf(o, "      scale 1.5\n" );
   fprintf(o, "   }\n" );
   fprintf(o, "}\n" );

   fclose(o);
   return(0);
}