// LightingEffects.inc

// POP Muzik
  // Olive - colors cycle yellow, red, green
  // Arch
  // Arch Lights
  // Speaker Lights
  // Stage Wrapper Lights
  // Behind Stage Lights
  // Speaker Tower Lights - colors cycle
// Mofo

// I Will Follow

// Gone

// Even Better Than The Real Thing

// Last Night On Earth

// Until The End Of The World

// New Year's Day

// Pride (In the Name of Love)

// I Still Haven't Found What I'm Looking For

// All I Want Is You

// Desire

// Staring At The Sun

// Sunday Bloody Sunday

// Bullet the Blue Sky

// Please

// Where the Streets Have No Name

// Lemon

// Discotheque-Life During Wartime

// If You Wear That Velvet Dress

// With or Without You

// Hold Me Thrill Me Kiss Me Kill Me

// Mysterious Ways

// One-Wake Up Dead Man
